kind: pipline
type: docker
name: default

steps:
  - name: build
    image: maven:3-jdk-11
    commands:
      - mvn -Dmaven.test.skip=true package
  - name: tests
    image: maven:3-jdk-11
    commands:
      - mvn test